/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pcc;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chaitanya
 */
public class BillReceipt extends javax.swing.JFrame {

    /**
     * Creates new form BillReceipt
     */
    public BillReceipt() {
        initComponents();
    }

    public BillReceipt(javax.swing.JTable OTable,javax.swing.JTextField OTotalTextField) {
        initComponents();
        int y = 184;
        DefaultTableModel model = (DefaultTableModel) OTable.getModel();
        javax.swing.JLabel[] particulars = new javax.swing.JLabel[model.getRowCount()];
                javax.swing.JLabel[] qty = new javax.swing.JLabel[model.getRowCount()];
                                javax.swing.JLabel[] price = new javax.swing.JLabel[model.getRowCount()];
                                javax.swing.JLabel[] rate = new javax.swing.JLabel[model.getRowCount()];
        for (int i = 0; i < model.getRowCount(); i++) {
            particulars[i] = new javax.swing.JLabel(OTable.getValueAt(i, 0).toString());
            this.add(particulars[i]);
            Dimension size = particulars[i].getPreferredSize();
            y += 12;
            particulars[i].setBounds(10, y, size.width, size.height);
            particulars[i].setVisible(true);
            
               qty[i] = new javax.swing.JLabel(OTable.getValueAt(i, 3).toString());
            this.add(qty[i]);
            Dimension size1 = qty[i].getPreferredSize();
            qty[i].setBounds(155, y, size1.width, size1.height);
            qty[i].setVisible(true);
            
            price[i] = new javax.swing.JLabel(OTable.getValueAt(i, 6).toString());
            this.add(price[i]);
            Dimension size2 = price[i].getPreferredSize();
            price[i].setBounds(295, y, size2.width, size2.height);
            price[i].setVisible(true);
            
            rate[i] = new javax.swing.JLabel((Float.parseFloat(OTable.getValueAt(i, 6).toString())/Float.parseFloat(OTable.getValueAt(i, 3).toString()))+"");
            this.add(rate[i]);
            Dimension size3 = rate[i].getPreferredSize();
            rate[i].setBounds(220, y, size3.width, size3.height);
            rate[i].setVisible(true);
        }
            javax.swing.JLabel line = new javax.swing.JLabel("--------------------------------------------------------------------------------------------");
            this.add(line);
            Dimension lineSize = line.getPreferredSize();
            line.setBounds(1, y+12, lineSize.width, lineSize.height);
            line.setVisible(true);
            
            javax.swing.JLabel totalAmount = new javax.swing.JLabel("Total :");
            this.add(totalAmount);
            Dimension totalAmountSize = totalAmount.getPreferredSize();
            totalAmount.setBounds(260, y+24, totalAmountSize.width, totalAmountSize.height);
            totalAmount.setVisible(true);
            
            javax.swing.JLabel line2 = new javax.swing.JLabel("--------------------------------------------------------------------------------------------");
            this.add(line2);
            Dimension line2Size = line2.getPreferredSize();
            line2.setBounds(1, y+35, line2Size.width, line2Size.height);
            line2.setVisible(true);
            
              javax.swing.JLabel totalAmountValue = new javax.swing.JLabel(OTotalTextField.getText());
            this.add(totalAmountValue);
            Dimension totalAmountValueSize = totalAmountValue.getPreferredSize();
            totalAmountValue.setBounds(298, y+24, totalAmountValueSize.width, totalAmountValueSize.height);
            totalAmountValue.setVisible(true);
            
            
              javax.swing.JButton RprintButton = new javax.swing.JButton("Print");
            this.add(RprintButton);
            Dimension RprintButtonSize = RprintButton.getPreferredSize();
            RprintButton.setBounds(160, y+54, RprintButtonSize.width, RprintButtonSize.height);
            RprintButton.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        RfirmNameLabel = new javax.swing.JLabel();
        RfirmAddressLabel = new javax.swing.JLabel();
        RfirmContactNoLabel = new javax.swing.JLabel();
        RbillTypeLabel = new javax.swing.JLabel();
        RbillNoLabel = new javax.swing.JLabel();
        RbillDateLabel = new javax.swing.JLabel();
        RbillTimeLabel = new javax.swing.JLabel();
        RparticularsLabel = new javax.swing.JLabel();
        RqtyLabel = new javax.swing.JLabel();
        RrateLabel = new javax.swing.JLabel();
        RamountLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RfirmNameLabel.setText("PUNJABI CHAAP CORNER");

        RfirmAddressLabel.setText("Shop No 2 , SECTOR-14 , GURUGRAM , 122001");

        RfirmContactNoLabel.setText("PH:7017271348");

        RbillTypeLabel.setText("Bill Type");

        RbillNoLabel.setText("Bill No");

        RbillDateLabel.setText("Bill Date");

        RbillTimeLabel.setText("Time");

        RparticularsLabel.setText("Particulars");

        RqtyLabel.setText("Qty");

        RrateLabel.setText("Rate");

        RamountLabel.setText("Amount");

        jLabel12.setText("------------------------------------------------------------------------------------------");

        jLabel13.setText("------------------------------------------------------------------------------------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RrateLabel)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RbillNoLabel)
                                        .addComponent(RbillTypeLabel)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(RbillDateLabel)
                                            .addGap(147, 147, 147)
                                            .addComponent(RbillTimeLabel))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RparticularsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RamountLabel)))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(RfirmContactNoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(RfirmNameLabel)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(RfirmAddressLabel)
                        .addGap(60, 60, 60))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(RqtyLabel)
                .addGap(190, 190, 190))
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(RfirmNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RfirmAddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RfirmContactNoLabel)
                .addGap(11, 11, 11)
                .addComponent(RbillTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RbillNoLabel)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbillDateLabel)
                    .addComponent(RbillTimeLabel))
                .addGap(2, 2, 2)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RparticularsLabel)
                    .addComponent(RqtyLabel)
                    .addComponent(RrateLabel)
                    .addComponent(RamountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BillReceipt b = new BillReceipt();
                b.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RamountLabel;
    private javax.swing.JLabel RbillDateLabel;
    private javax.swing.JLabel RbillNoLabel;
    private javax.swing.JLabel RbillTimeLabel;
    private javax.swing.JLabel RbillTypeLabel;
    private javax.swing.JLabel RfirmAddressLabel;
    private javax.swing.JLabel RfirmContactNoLabel;
    private javax.swing.JLabel RfirmNameLabel;
    private javax.swing.JLabel RparticularsLabel;
    private javax.swing.JLabel RqtyLabel;
    private javax.swing.JLabel RrateLabel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
        /*PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setJobName(" Print Component ");
        pj.setPrintable(new Printable() {
            @Override
            public int print(Graphics pg, PageFormat pf, int pageNum) {
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                new BillReceipt().paint(g2);
                return Printable.PAGE_EXISTS;
            }
        });

        if (pj.printDialog() == false) {
            return;
        }

        try {
            pj.print();
        } catch (PrinterException ex) {
            // handle exception
        }*/
