/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pcc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author bansa
 */
public class DeleteItem extends javax.swing.JFrame {

    /**
     * Creates new form DeleteItem
     */
    public DeleteItem() {
        initComponents();
        fillDICategoryComboBox();
    }
    public void fillDICategoryComboBox()
    {
        DICategoryComboBox.removeAllItems();
        DIItemNameComboBox.removeAllItems();
            try
        {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pcc","root","");
            Statement st = conn.createStatement(); 
            String query = "SELECT DISTINCT ITEM_CATEGORY FROM item";
            ResultSet set = st.executeQuery(query);
            while(set.next())
            {
                System.out.println(set.getString("ITEM_CATEGORY"));
                DICategoryComboBox.addItem(set.getString("ITEM_CATEGORY"));                
            }
        }catch(SQLException ex)
        {
                Logger.getLogger(AdminDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void fillDIItemComboBox()
    {
            
            String si = (String)DICategoryComboBox.getSelectedItem();
            try
        {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pcc","root","");
            Statement st = conn.createStatement(); 
            String query = "SELECT ITEM_NAME FROM item WHERE ITEM_CATEGORY = '"+si+"'";
            ResultSet set = st.executeQuery(query);
            while(set.next())
            {
                System.out.println(set.getString("ITEM_NAME"));
                DIItemNameComboBox.addItem(set.getString("ITEM_NAME"));                
            }
        }catch(SQLException ex)
        {
                Logger.getLogger(AdminDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DIItemNameLabel = new javax.swing.JLabel();
        DICategoryLabel = new javax.swing.JLabel();
        DICategoryComboBox = new javax.swing.JComboBox();
        DIItemNameComboBox = new javax.swing.JComboBox();
        DIDeleteItemButton = new javax.swing.JButton();
        DIResetButton = new javax.swing.JButton();
        DICloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DIItemNameLabel.setText("Select Item Name");

        DICategoryLabel.setText("Select Category");

        DICategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DICategoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DICategoryComboBoxActionPerformed(evt);
            }
        });

        DIItemNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DIDeleteItemButton.setText("Delete Item");
        DIDeleteItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIDeleteItemButtonActionPerformed(evt);
            }
        });

        DIResetButton.setText("Reset");

        DICloseButton.setText("Close");
        DICloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DICloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DICategoryLabel)
                    .addComponent(DIItemNameLabel))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DICategoryComboBox, 0, 139, Short.MAX_VALUE)
                    .addComponent(DIItemNameComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(DIDeleteItemButton)
                .addGap(28, 28, 28)
                .addComponent(DIResetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(DICloseButton)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DICategoryLabel)
                    .addComponent(DICategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DIItemNameLabel)
                    .addComponent(DIItemNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DIDeleteItemButton)
                    .addComponent(DIResetButton)
                    .addComponent(DICloseButton))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DICategoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DICategoryComboBoxActionPerformed
        // TODO add your handling code here:
                DIItemNameComboBox.removeAllItems();
                fillDIItemComboBox();

    }//GEN-LAST:event_DICategoryComboBoxActionPerformed

    private void DIDeleteItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIDeleteItemButtonActionPerformed
        // TODO add your handling code here:
        
        String ic = (String)DICategoryComboBox.getSelectedItem();
        String in = (String)DIItemNameComboBox.getSelectedItem();
               try
        {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pcc","root","");
            Statement st = conn.createStatement(); 
            String query1 = "DELETE FROM item WHERE ITEM_NAME = '"+in+"' AND ITEM_CATEGORY = '"+ic+"'";
            String query2 = "DELETE FROM inventory WHERE ITEM_NAME = '"+in+"'";
            int i = st.executeUpdate(query1);
            int j = st.executeUpdate(query2);
            if(i == 1 && j == 1)
            {
                JOptionPane optionPane = new JOptionPane("Data Deleted",JOptionPane.OK_OPTION);
                JDialog dialog = optionPane.createDialog("Success!");
                dialog.setAlwaysOnTop(true); // to show top of all other application
                dialog.setVisible(true); // to visible the dialog
            }
         
        }catch(SQLException ex)
        {
                Logger.getLogger(AdminDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_DIDeleteItemButtonActionPerformed

    private void DICloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DICloseButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_DICloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DICategoryComboBox;
    private javax.swing.JLabel DICategoryLabel;
    private javax.swing.JButton DICloseButton;
    private javax.swing.JButton DIDeleteItemButton;
    private javax.swing.JComboBox DIItemNameComboBox;
    private javax.swing.JLabel DIItemNameLabel;
    private javax.swing.JButton DIResetButton;
    // End of variables declaration//GEN-END:variables
}
